site_name: Horizon Documentation
site_url:  https://harukumo.github.io/Horizon-Documentation/
theme: readthedocs

nav:
    - Home: index.md
    - About: about.md
    - Roadmap: roadmap.md
    - Manual: manual/basics.md